version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: wastewatch_backend
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: wastewatch_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
